const state={recipes:[],aliases:{},favorites:new Set(JSON.parse(localStorage.getItem('polarisFavorites')||'[]')),selectedIngredients:new Set(),category:null,currentRecipe:null,cookStep:0,checkedSteps:new Set(),viewHistory:['homeView']};
const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
const pantry=new Set(['соль','черный перец','масло растительное','масло сливочное','вода','сахар']);
function saveFav(){localStorage.setItem('polarisFavorites',JSON.stringify([...state.favorites]));updateFavCount()}
function updateFavCount(){$('#favCount').textContent=state.favorites.size||''}
function canonicalize(x){let v=x.toLowerCase().trim();return state.aliases[v]||v}
function allIngredients(){const map=new Map();state.recipes.forEach(r=>Object.keys(r.ingredients||{}).forEach(raw=>{const id=canonicalize(raw);if(!map.has(id))map.set(id,{id,name:prettyName(id),count:0});map.get(id).count++}));return [...map.values()].sort((a,b)=>a.name.localeCompare(b.name,'ru'))}
function prettyName(x){return x.replace(/\b\S/g,c=>c.toUpperCase())}
function showView(id,push=true){$$('.view').forEach(v=>v.classList.remove('active'));$('#'+id).classList.add('active');if(push)state.viewHistory.push(id);const navId=['homeView','ingredientsView','indexView','favoritesView'].includes(id)?id:'homeView';$$('.nav-item').forEach(n=>n.classList.toggle('active',n.dataset.nav===navId));window.scrollTo(0,0)}
function renderCategories(){const cats=[...new Set(state.recipes.map(r=>r.category).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'ru'));$('#categories').innerHTML=cats.map(c=>`<button class="chip ${state.category===c?'active':''}" data-cat="${esc(c)}">${esc(c)}</button>`).join('');$$('[data-cat]').forEach(b=>b.onclick=()=>{state.category=state.category===b.dataset.cat?null:b.dataset.cat;renderCategories();renderHome()})}
function renderHome(){const q=$('#searchInput').value.trim().toLowerCase();let list=state.recipes.filter(r=>(!state.category||r.category===state.category)&&(!q||r.search_text?.toLowerCase().includes(q)||r.title.toLowerCase().includes(q)));$('#resultsTitle').textContent=state.category||'Все рецепты';$('#resultsCount').textContent=list.length+' шт.';$('#recipeList').innerHTML=list.map(recipeHtml).join('')||empty('Ничего не найдено');bindRecipeItems()}
function recipeHtml(r,missing=null){const fav=state.favorites.has(r.id);return `<div class="recipe-item" data-recipe="${esc(r.id)}"><button class="fav-btn" data-fav="${esc(r.id)}">${fav?'★':'☆'}</button><h3>${esc(r.title)}</h3><div class="recipe-meta"><span>⏱ ${r.time_minutes||'?'} мин</span><span>⚙ ${esc(r.mode||'—')}</span><span>${esc(r.category||'')}</span>${missing!==null?`<span>Не хватает: ${missing}</span>`:''}</div></div>`}
function bindRecipeItems(){$$('[data-recipe]').forEach(x=>x.onclick=e=>{if(e.target.closest('[data-fav]'))return;openRecipe(x.dataset.recipe)});$$('[data-fav]').forEach(b=>b.onclick=e=>{e.stopPropagation();toggleFav(b.dataset.fav)})}
function toggleFav(id){state.favorites.has(id)?state.favorites.delete(id):state.favorites.add(id);saveFav();renderHome();renderFavorites();if(state.currentRecipe?.id===id)updateRecipeFav()}
function renderFavorites(){const list=state.recipes.filter(r=>state.favorites.has(r.id));$('#favoritesList').innerHTML=list.map(recipeHtml).join('')||empty('Пока нет избранных рецептов');bindRecipeItems()}
function openRecipe(id){const r=state.recipes.find(x=>x.id===id);if(!r)return;state.currentRecipe=r;state.checkedSteps=new Set();$('#recipeCard').innerHTML=`<div class="recipe-hero"><div class="muted">${esc(r.category||'')}</div><h2>${esc(r.title)}</h2><div class="recipe-stats"><span class="stat">⏱ ${r.time_minutes||'?'} мин</span><span class="stat">⚙ ${esc(r.mode||'—')}</span>${r.temperature_c?`<span class="stat">🌡 ${r.temperature_c}°C</span>`:''}</div></div><details class="accordion" open><summary>Ингредиенты</summary><div class="accordion-body">${Object.entries(r.ingredients||{}).map(([k,v])=>`<div class="ingredient-line"><span>${esc(prettyName(canonicalize(k)))}</span><b>${esc(v)}</b></div>`).join('')}</div></details><details class="accordion" open><summary>Приготовление</summary><div class="accordion-body">${(r.steps||[]).map((s,i)=>`<label class="check-step"><input type="checkbox" data-step="${i}"><span><b>${i+1}.</b> ${esc(s)}</span></label>`).join('')}<button id="startCook" class="cook-btn">▶ Готовить пошагово</button></div></details>${r.tags?.length?`<details class="accordion"><summary>Теги</summary><div class="accordion-body muted">${r.tags.map(esc).join(' · ')}</div></details>`:''}`;$$('[data-step]').forEach(c=>c.onchange=()=>c.checked?state.checkedSteps.add(+c.dataset.step):state.checkedSteps.delete(+c.dataset.step));$('#startCook').onclick=startCooking;updateRecipeFav();showView('recipeView')}
function updateRecipeFav(){$('#favoriteRecipe').textContent=state.favorites.has(state.currentRecipe?.id)?'★':'☆'}
function startCooking(){state.cookStep=0;state.checkedSteps=new Set();renderCook();showView('cookView')}
function renderCook(){const r=state.currentRecipe, steps=r.steps||[];$('#cookTitle').textContent=r.title;$('#cookProgress').textContent=`${Math.min(state.cookStep+1,steps.length)} / ${steps.length}`;$('#cookStep').textContent=steps[state.cookStep]||'Готово!';$('#prevStep').disabled=state.cookStep===0;$('#nextStep').textContent=state.cookStep===steps.length-1?'✓':'→';$('#stepDone').textContent=state.checkedSteps.has(state.cookStep)?'Выполнено ✓':'Готово ✓';$('#cookDots').innerHTML=steps.map((_,i)=>`<span class="dot ${i===state.cookStep?'active':''}"></span>`).join('')}
function step(delta){const n=state.currentRecipe.steps.length;if(delta>0&&state.cookStep<n-1){state.checkedSteps.add(state.cookStep);state.cookStep++}else if(delta<0&&state.cookStep>0)state.cookStep--;renderCook()}
function renderIngredientFilter(){const q=$('#ingredientSearch').value.toLowerCase();const items=allIngredients().filter(x=>x.name.toLowerCase().includes(q));$('#ingredientFilter').innerHTML=items.map(x=>`<button class="ingredient-check ${state.selectedIngredients.has(x.id)?'selected':''}" data-ing="${esc(x.id)}">${esc(x.name)}<small>${x.count} ${plural(x.count,'рецепт','рецепта','рецептов')}</small></button>`).join('');$$('[data-ing]').forEach(b=>b.onclick=()=>{const id=b.dataset.ing;state.selectedIngredients.has(id)?state.selectedIngredients.delete(id):state.selectedIngredients.add(id);renderIngredientFilter();renderIngredientResults()});$('#selectedCount').textContent=state.selectedIngredients.size?`Выбрано: ${state.selectedIngredients.size}`:''}
function renderIngredientResults(){const selected=[...state.selectedIngredients];let ranked=state.recipes.map(r=>{const ids=new Set(Object.keys(r.ingredients||{}).map(canonicalize));const missing=selected.filter(x=>!ids.has(x)).length;const matched=selected.length-missing;return {r,missing,matched}}).filter(x=>selected.length===0||x.matched>0).sort((a,b)=>a.missing-b.missing||b.matched-a.matched||a.r.title.localeCompare(b.r.title,'ru'));$('#matchCount').textContent=ranked.length+' шт.';$('#ingredientResults').innerHTML=ranked.map(x=>recipeHtml(x.r,x.missing)).join('')||empty('Нет подходящих рецептов');bindRecipeItems()}
function renderIndex(){const q=$('#indexSearch').value.toLowerCase();const items=allIngredients().filter(x=>x.name.toLowerCase().includes(q));let last='';let html='';for(const x of items){const l=x.name[0].toUpperCase();if(l!==last){last=l;html+=`<div class="index-letter">${esc(l)}</div>`}html+=`<button class="index-item" data-index-ing="${esc(x.id)}"><span>${esc(x.name)}</span><span class="muted">${x.count}</span></button>`}$('#subjectIndex').innerHTML=html||empty('Ничего не найдено');$$('[data-index-ing]').forEach(b=>b.onclick=()=>{state.selectedIngredients=new Set([b.dataset.indexIng]);showView('ingredientsView');renderIngredientFilter();renderIngredientResults()})}
function empty(t){return `<div class="recipe-item muted">${t}</div>`}
function plural(n,a,b,c){const x=n%100;return x>=11&&x<=19?c:(n%10===1?a:(n%10>=2&&n%10<=4?b:c))}
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]))}
async function init(){try{const response=await fetch('data/recipes.json',{cache:'no-cache'});if(!response.ok)throw new Error('HTTP '+response.status);const data=await response.json();state.recipes=data.recipes||[];state.aliases=data.ingredient_aliases||{};renderCategories();renderHome();renderIngredientFilter();renderIngredientResults();renderIndex();updateFavCount();registerSW()}catch(e){console.error('Ошибка загрузки базы рецептов:',e);$('#recipeList').innerHTML=empty('Не удалось загрузить базу. Откройте приложение через run-local.bat или HTTPS-хостинг.')}}
function registerSW(){if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js').catch(()=>{})}
$('#searchInput').oninput=renderHome;$('#ingredientSearch').oninput=renderIngredientFilter;$('#indexSearch').oninput=renderIndex;$('#clearIngredients').onclick=()=>{state.selectedIngredients.clear();renderIngredientFilter();renderIngredientResults()};$('#allRecipesBtn').onclick=()=>{state.category=null;renderCategories();renderHome()};$('#favoriteRecipe').onclick=()=>toggleFav(state.currentRecipe.id);$('#recipeBack').onclick=()=>showView('homeView');$('#cookBack').onclick=()=>showView('recipeView');$('#prevStep').onclick=()=>step(-1);$('#nextStep').onclick=()=>step(1);$('#stepDone').onclick=()=>{state.checkedSteps.add(state.cookStep);if(state.cookStep<state.currentRecipe.steps.length-1)state.cookStep++;renderCook()};$$('[data-action]').forEach(b=>b.onclick=()=>{const a=b.dataset.action;showView(a==='ingredients'?'ingredientsView':'indexView');a==='ingredients'?renderIngredientFilter():renderIndex()});$$('[data-back]').forEach(b=>b.onclick=()=>showView('homeView'));$$('[data-nav]').forEach(b=>b.onclick=()=>{showView(b.dataset.nav);if(b.dataset.nav==='favoritesView')renderFavorites();if(b.dataset.nav==='ingredientsView'){renderIngredientFilter();renderIngredientResults()}if(b.dataset.nav==='indexView')renderIndex()});let sx=0;$('#cookStep').addEventListener('touchstart',e=>sx=e.changedTouches[0].screenX,{passive:true});$('#cookStep').addEventListener('touchend',e=>{const dx=e.changedTouches[0].screenX-sx;if(Math.abs(dx)>60)step(dx<0?1:-1)},{passive:true});init();
